### ISSUE TITLE
404 link to gimp repositry

### ISSUE THREAD

**Issue by mangelozzi** [bootchk/resynthesizer#110]
The following link for installing it (from https://logarithmic.net/pfh/resynthesizer) results in a 404
https://www.gimp.org/registry/node/25219

**Comment by bootchk** [comment]
I cannot control the links at another website, owned by the original author.

See the Wiki here for instructions how to download.

**Comment by mangelozzi** [comment]
> 

Ok I see,  thanks for taking the project over. PS the wikie is a blank page: https://github.com/bootchk/resynthesizer/wiki/Install-Resynthesizer-from-a-package-manager
