### ISSUE TITLE
VERY IMPORTANT! Someone is changing download links on the wiki to malware.

### ISSUE THREAD

**Issue by Looki2000** [bootchk/resynthesizer#138]
just look at the history
https://github.com/bootchk/resynthesizer/wiki/Install-Resynthesizer/_history
I tried to download the latest one, but both Windows unzip tool and 7zip reported error with the archive. I then I noticed it's 62MB and the URL is not from GitHub. Am I already screwed?

**Comment by Looki2000** [comment]
Okay, I now confirmed it's malicious and it errored only because there was extra new line in the beginning of the file. I scanned the other URL he put on VirusTotal and its 14/68.
https://www.virustotal.com/gui/file/922374c3ab996c788fd04e44d146184ddec1e6d00535a53e9dc7a52c3ca4aa49/detection
Why is the wiki editable by anybody? Someone has to change that urgently.

**Comment by bootchk** [comment]
I removed permissions for anyone to edit.
Now only collaborators.

AFAIK the links are not malware now.
If you discover otherwise, please let me know exactly which link is wrong.

Thanks.
