### ISSUE TITLE
Please provide Windows binaries

### ISSUE THREAD

**Issue by CamiloMM** [bootchk/resynthesizer#17]
I'm a developer, but I never touched MinGW before. I tried for whole hours to set it up correctly on more than one VM, but always I get various errors, frustration, and sadness.

I cannot possibly imagine a non-developer could ever hope to use your (supposedly awesome) plugin on Windows. Heck, even the sample images seem to be PPMs instead of PNGs.

Considering that Gimp is such a good gateway for people on Windows to consider switching to Linux, I think it should be friendly to them, so I urge you to please consider providing Windows binaries, since it looks like you could make them.

Thank you in advance.

**Comment by LeBaux** [comment]
@bootchk I know this topic is from 2013 but still relevant. Maybe you should list the binaries on release page or at least put a note into readme please. For less technically apt, using your plugins might be a real challenge. Thanks and thanks! :)

**Comment by bootchk** [comment]
I added links to the readme.
