### ISSUE TITLE
Heal selection doesn't show up in Enhancement menu

### ISSUE THREAD

**Issue by jonnyrobbie** [bootchk/resynthesizer#26]
Arch linux:

    $ pacman -Q gimp-git gimp-plugin-resynthesizer-git
    gimp-git 20150908.gdf2a485-1
    gimp-plugin-resynthesizer-git 2.0.r15.g462b0b7-1

those python plugins are where they are supposed to be (I think) with exec flags alright:

    $ ls -la /usr/lib/gimp/2.0/plug-ins/plugin-*
    -rwxr-xr-x 1 root root 23424 Sep  8 23:01 /usr/lib/gimp/2.0/plug-ins/plugin-browser
    -rwxr-xr-x 1 root root  6596 Sep  9 03:28 /usr/lib/gimp/2.0/plug-ins/plugin-heal-selection.py
    -rwxr-xr-x 1 root root  3154 Sep  9 03:28 /usr/lib/gimp/2.0/plug-ins/plugin-heal-transparency.py
    -rwxr-xr-x 1 root root 17195 Sep  9 03:28 /usr/lib/gimp/2.0/plug-ins/plugin-map-style.py
    -rwxr-xr-x 1 root root  7685 Sep  9 03:28 /usr/lib/gimp/2.0/plug-ins/plugin-render-texture.py
    -rwxr-xr-x 1 root root  3304 Sep  9 03:28 /usr/lib/gimp/2.0/plug-ins/plugin-resynth-enlarge.py
    -rwxr-xr-x 1 root root  3610 Sep  9 03:28 /usr/lib/gimp/2.0/plug-ins/plugin-resynth-fill-pattern.py
    -rwxr-xr-x 1 root root  3263 Sep  9 03:28 /usr/lib/gimp/2.0/plug-ins/plugin-resynth-sharpen.py
    -rwxr-xr-x 1 root root  6012 Sep  9 03:28 /usr/lib/gimp/2.0/plug-ins/plugin-uncrop.py

but nothing shows up in enhancement menu: http://i.imgur.com/4UfnumE.png

I've tries copying those python scripts to respective home config:

    $ ls -la ~/.config/GIMP/2.9/plug-ins/
    total 116
    drwxr-xr-x  2 marek users  4096 Sep 10 20:02 .
    drwxr-xr-x 25 marek users  4096 Sep 11 12:07 ..
    -rwxr-xr-x  1 marek users  6596 Sep  9 03:28 plugin-heal-selection.py
    -rwxr-xr-x  1 marek users  3154 Sep  9 03:28 plugin-heal-transparency.py
    -rwxr-xr-x  1 marek users 17195 Sep  9 03:28 plugin-map-style.py
    -rwxr-xr-x  1 marek users  7685 Sep  9 03:28 plugin-render-texture.py
    -rwxr-xr-x  1 marek users  3304 Sep  9 03:28 plugin-resynth-enlarge.py
    -rwxr-xr-x  1 marek users  3610 Sep  9 03:28 plugin-resynth-fill-pattern.py
    -rwxr-xr-x  1 marek users  3263 Sep  9 03:28 plugin-resynth-sharpen.py
    -rwxr-xr-x  1 marek users 31592 Sep  9 03:28 resynthesizer
    -rwxr-xr-x  1 marek users 23560 Sep  9 03:28 resynthesizer_gui

Didn't help. The curious thing is that I have *Filters->Map->Resynthesize* allright. I saw #21 and I don't fully understand how to emulate that Heal Selection with Resynthesize. I've tried cloning/selecting/sourcing all I could think of, but all it did was just warp things in the selection.

**Comment by bootchk** [comment]
Thanks.  Your analysis seems correct.  I don't understand it either.

The Resynthesize menu item comes from resynthesizer_gui executable, which is written in C.   The Heal Selection item comes from a Python script.  All I can think of is that Python or PyGimp is not starting correctly.  Note that Gimp only reads the Python plugins once, at startup.  IOW, restarting Gimp is required after installing Python plugins.  Please let me know whether that works.

I also considered that maybe something has changed in GIMP 2.9 but a quick search that others seem to be able to still use Resynthesizer with GIMP 2.9.

I am not familiar with Arch Linux.  So I might need to read about pacman and the -git scripts, I don't know who wrote those, it is remotely possible they are flawed.

**Comment by jonnyrobbie** [comment]
Restarting gimp didn't help. I've tried deleting `~/.config/GIMP/2.9/pluginrc` and restarting, but it didn't help. Starting gimp with --verbose flag: http://pastebin.com/b2CZyu5s

After that, I downgraded from gimp-git (2.9) to gimp stable (2.8) and the plugin now works fine. So it really is a problem with 2.9. I've read that devs are doing some substantioal things with gegl and maybe something changed about python too.

**Comment by bootchk** [comment]
Thanks.  The trace from --verbose seems to indicate that gimp is trying to invoke 'python2', which cannot be found.  Try entering that on a command line, or 'which python2', ('which' is a command that tells you how a command is resolved, the path to an executable, more or less.)  Or you could test some other Gimp plugin written in Python (off the top of my head, I don't know whether any ship with Gimp.)  I would guess that most linux distros have a symbolic link from python2 to some version of python executable.  Could that link be missing?  Possibly gimp should not be invoking 'python2', but just 'python' (I am not expert at python installations, they can be confusing especially with python3 etc.)

I am not familiar with gimp compatibility, but I would hope that for minor versions (2.9, etc.) they would not break external plugins.  So I am dubious about the problem being in Gimp 2.9.

**Comment by jonnyrobbie** [comment]
$ which python2; python --version; python2 --version
    /usr/bin/python2
    Python 3.4.3
    Python 2.7.10

**Comment by bootchk** [comment]
OK.  I just searched and found your thread on reddit.  There you say that the plugin .py scripts have a shebang of ....python2.  But it seems like that is not the case in my git repository.  So maybe gimp-git is changing them?   In the shebang, does /usr/bin/env establish a different env than your personal env?  Still thinking...

**Comment by bootchk** [comment]
In AUR gimp-git.git there is this:

  make DESTDIR="$pkgdir/" install
#  sed -i 's|#!/usr/bin/env python|#!/usr/bin/env python2|' "${pkgdir}"/usr/lib/gimp/2.0/plug-ins/*.py
  install -D -m644 "${srcdir}/linux.gpl" "${pkgdir}/usr/share/gimp/2.0/palettes/Linux.gpl"

i.e. gimp-git has a commented out line that was (?not in the latest version) mangling python to python2

I am not familiar with Arch, but this seems relevant.

**Comment by bootchk** [comment]
See this thread:

https://aur.archlinux.org/packages/gimp-git/

A snippet:

@mytbk: You may want to remove the line that's sedding out the 

env python

from the PKGBUILD because specifying PYTHON=/usr/bin/python2 before the autogen.sh already takes care of converting the python interpreter (see the generated /usr/lib/gimp/2.0/interpreters/pygimp.interp after you build the package). 

When the sed is performed, it prevents ALL of gimp's default python-based plugins from running. Peculiarly, scripts with the env python line left alone still execute fine. I found this out when I saw my Permute Layers plugin still around in gimp 2.9, but not the built-in openraster plugin for gimp.

**Comment by mytbk** [comment]
@bootchk It's aur/gimp-plugin-resynthesizer-git that sed the '/usr/bin/env python' to '/usr/bin/env python2'.

After I change python2 to python in one of the plugin script, that plugin script can be loaded in aur/gimp-git. I'm also curious why this can happen.

**Comment by bootchk** [comment]
OK.  As I said previously, maybe the shebang environment has no python2 defined.

If you are in the Arch community, please file a bug report on ...resynthesizer-git.

**Comment by jonnyrobbie** [comment]
ok, commenting out the sed line (line 27) in the aur's gimp-plugin-resynthesizer-git PKGBUILD got around the issue. I still don't think it's completely solved, but at least it works now.
