### ISSUE TITLE
Use in iOS app?

### ISSUE THREAD

**Issue by rsmoz** [bootchk/resynthesizer#27]
Trying to figure out how to use this in an iOS application. I want to be able to take an image and image mask and run it through the heal algorithm. I tried dropping all the files into an Xcode project, but of course that doesn't retain any of the specific build configuration stuff that's in this repo. Any advice on how to get this building in an iOS project?

**Comment by bootchk** [comment]
You only need to build the inner library, and call it.  See the README under architecture.  I suggest you create a simple makefile to build the library and compile via the command line.  There is a simple makefile.bootchk in the repository, that is probably obsolete but might be hacked.  The inner library is simple and has few dependencies (just libm) after you set a compile time flag to use a proxy for libgthread.  I suppose you could also configure Xcode to build the library.

Are you planning to  publish the app? Which I think is certainly OK under the license.  I'm just wondering if there isn't already an app and how useful it would be to have an app that only heals and does nothing else.
