### ISSUE TITLE
Please include appdata in your package

### ISSUE THREAD

**Issue by luyatshimbalanga** [bootchk/resynthesizer#31]
[Appdata file](https://bugzilla.redhat.com/show_bug.cgi?id=1316714) is already set up  for you add-on (click the attachment), please check if all information is correct. The reason is [Gnome Software](https://www.wikiwand.com/en/GNOME_Software) (which is also featured in Ubuntu) is running appstream allowing an easier installation.

Check the guideline on:
https://www.freedesktop.org/software/appstream/docs/sect-Quickstart-Addons.html

Fedora also has an useful information about the process:
https://fedoraproject.org/wiki/Packaging:AppData

**Comment by bootchk** [comment]
OK, done.  Thanks.
