### ISSUE TITLE
Use Resynthesizer in my application

### ISSUE THREAD

**Issue by anandcu3** [bootchk/resynthesizer#40]
Is it possible to use the Heal Selection Feature as part of our application like a Python Library without using gimp?

**Comment by bootchk** [comment]
Short answer: no, not easy.

Resynthesizer architecture encapsulates the algorithm in a library, but there is no Python binding to the library.  Besides, I don't know if there is a "standard" representation of images in Python.

This [post on StackOverflow](https://stackoverflow.com/questions/8196210/how-to-use-gimp-inside-a-python-script) discusses other ideas, none off the shelf.

The author of the best answer in that post also has [Python-Gegl](https://pypi.python.org/pypi/python-gegl/0.2.1).  Resynthesizer  algorithm library could be wrapped as a Gegl operation, but it currently is not.  If it were, then maybe you could call Python-Gegl from Python and invoke the Resynthesizer operation?

**Comment by bootchk** [comment]
Since this is not an issue, just a question or a request for enhancement, I am closing the issue.
