### ISSUE TITLE
Heal selection doesn't work

### ISSUE THREAD

**Issue by katarzynapawelczak** [bootchk/resynthesizer#49]
I've got that error when I tried to use heal selection tool:
![image](https://user-images.githubusercontent.com/7593033/38341537-5f42ee74-3879-11e8-8dd4-cbb0254c6ee2.png)

**Comment by bootchk** [comment]
Sorry for the late response.  I missed any notification you opened an issue.

What version of Resynthesizer and GIMP, and is it a 32-bit or 64-bit build?  Another issue says there are problems (with different symptoms) with 32-bit build of Resynthesizer used with 64-bit build of GIMP, starting with GIMP 2.10 release.

Also, is there anything peculiar about the image Resynthesizer failed on?  From your screenshot, it looks like it has much transparency (and maybe many layers?)  If this is still an issue, could you share  the image (not flattened) and describe what steps you were taking?

**Comment by bootchk** [comment]
Closed for lack of response.
