### ISSUE TITLE
Resynthesizer link  file plugin broken.

### ISSUE THREAD

**Issue by xdanielsb** [bootchk/resynthesizer#54]
The current link for linux resynthesizer is broken.

**Comment by bootchk** [comment]
OK, thanks,  yes, I need to update the readme, since the link is broken, and the executable which it pointed to is 32-bit, which doesn't work for newer GIMP versions.  I also need to fix an issue with flatpack installs, and then I will commit another release.

**Comment by bootchk** [comment]
Closed by commit https://github.com/bootchk/resynthesizer/commit/f040bc4bdf61b9b76275c010264e789173f74833
