### ISSUE TITLE
Resynthesizer is extremely slow

### ISSUE THREAD

**Issue by HJarausch** [bootchk/resynthesizer#56]
Is it only me?
I've used  (Gimp) Filters -> Enhance -> Sharpen by synthesis on a 20Mpixel image.
After 1 hour CPU time I had to kill it without any result.

Gimp was running on a AMD Ryzen Threadripper 1950X 16-Core Processor with 64 Gb RAM.
I've compiled both Gimp and resynthesizer with -O3 gcc flag.

What am I missing?
Many thanks for a hint,
Helmut.

**Comment by bootchk** [comment]
It is not just you, but it is the nature of Sharpen.  That is a large image.  For sharpen, the whole image is the target.  Compare to Heal Selection, where only a small selection is the target.  If you start with a 20M image, Sharpen would create a 80M image, and then sharpen it (I think that is the right math.)  The algorithm is memory intensive, and depends on cache coherency.  I can imagine that is slow, but I admit I have not tested it.  

Finally, but why?  A 20M image is sharp enough unless you are creating billboards.  If you are creating billboards, my apologies, and I am interested in the details.
