### ISSUE TITLE
Links in Readme don't work anymore

### ISSUE THREAD

**Issue by osartun** [bootchk/resynthesizer#60]
There are three links in the **Quickstart** section of this repo's Readme and unfortunately none of them works.
<img width="664" alt="screen shot 2018-11-30 at 20 16 01" src="https://user-images.githubusercontent.com/1381730/49309848-d9de3100-f4dc-11e8-9e26-e15cc4466c87.png">

* http://registry.gimp.org seems to not exist anymore
* http://gimp.lisanet.de/Website/Download.html is a 404 page

(I'm completely new to Gimp and just downloaded it on Mac to have the content aware fill feature without buying Photoshop, but apparently getting this is way harder than I thought)

**Comment by Aster-the-Med-Stu** [comment]
@osartun Nah [Wayback Machine](https://web.archive.org/web/20180225174428/http://registry.gimp.org/node/27986) by archive.org works, and according to a developer of GIMP, they are developing a new plugin system.

**Comment by Artoria2e5** [comment]
There is also a static mirror at https://github.com/pixlsus/registry.gimp.org_static/blob/master/registry.gimp.org/node/27986. The Linux link is https://github.com/pixlsus/registry.gimp.org_static/blob/master/registry.gimp.org/files/resynthesizer.tar_0.gz and the Windows link is https://github.com/pixlsus/registry.gimp.org_static/blob/master/registry.gimp.org/files/Resynthesizer_v1.0-i686.zip.
