### ISSUE TITLE
lost library's and error 0x000007b 

### ISSUE THREAD

**Issue by Pumpkin-Studios** [bootchk/resynthesizer#65]
befor my gimp 2.10 works good
after to install gimp 2.10.12
fuckoff...

![csrss_2019-06-23_21-05-08](https://user-images.githubusercontent.com/42666929/59986185-4052aa00-95fb-11e9-8dcd-315f8da848bf.png)

![gimp-2 10_2019-06-23_21-05-47](https://user-images.githubusercontent.com/42666929/59986194-49dc1200-95fb-11e9-8657-14ba2b8aec64.png)

**Comment by bootchk** [comment]
How does this concern the resynthesizer plugin?

**Comment by Pumpkin-Studios** [comment]
it simply does not work, has never worked and is not corrected, and uninstall everything completely and reinstall from scratch and remains the same, remove all traces of gimp before reinstalling and continue with the same error

**Comment by Pumpkin-Studios** [comment]
> How does this concern the resynthesizer plugin?

it simply does not work, has never worked and is not corrected, and uninstall everything completely and reinstall from scratch and remains the same, remove all traces of gimp before reinstalling and continue with the same error
