### ISSUE TITLE
Error occurred running python_fu_heal_selection (GIMP 2.10.18/20)

### ISSUE THREAD

**Issue by SimoneStarace** [bootchk/resynthesizer#76]
### What I did.
I have installed GIMP on **Zorin OS** (distro based from Ubuntu) using the **snap** command, so I could get the latest version of the software, downloaded the plugin from the link given on the **[README](https://github.com/bootchk/resynthesizer/blob/master/README.md#quickstart)** file and extracted the files.
By installing GIMP using the snap command it makes a folder called **snap** inside my **HOME** folder and when I run GIMP every setting file is made inside this folder.
After this I putted the plugin files inside the folder plug-ins and changed the permissions for execute the plugin inside Gimp.

### What I got.
When I try to run the Heal Selection filter I got this error:

> Traceback (most recent call last):
>   File "/usr/lib/gimp/2.0/python/gimpfu.py", line 740, in response
>     dialog.res = run_script(params)
>   File "/usr/lib/gimp/2.0/python/gimpfu.py", line 361, in run_script
>     return apply(function, params)
>   File "/home/simon/snap/gimp/252/.config/GIMP/2.10/plug-ins/plugin-heal-selection.py", line 148, in heal_selection
>     pdb.plug_in_resynthesizer(timg, tdrawable, 0,0, useBorder, work_drawable.ID, -1, -1, 0.0, 0.117, 16, 500)
> error: procedure not found

In the end the plugin doesn't find a procedure.
Can someone help me with this problem?

**Comment by bootchk** [comment]
The error means that Gimp could not find the C language plugin, which is the "engine" that the Python language plugin calls.  Please verify that an executable file named "resynthesizer" is also installed in the same directory as other plugins, in your case /home/simon/snap/gimp/252/.config/GIMP/2.10/plug-ins.

**Comment by SimoneStarace** [comment]
Hi @bootchk thanks for answering me.
I have putted all the plugin files inside the folder _/home/simon/snap/gimp/252/.config/GIMP/2.10/plug-ins_.
That's why I found it strange that GIMP is giving me this error because I have also putted the Layer-Cut-Copy plugin inside the same folder and it works but this one it doesn't.

**Comment by bootchk** [comment]
My question for you is: does the file "resynthesizer" exist in that directory?

My prior answer intends to say:  each Python plugin in the resynthesizer package calls a second C-language plugin called "resynthesizer".  No Python plugin in the resynthesizer package will work if said second "resynthesizer" plugin is missing, and will give the error message you received.

You say you have put "all" the files in the directory, but please post a directory listing (use "ls -al" to show the size and execute permissions of the files) to prove it.  In my experience, in this case, it is best to assume that the installation is not correct.  If you prove the installation is correct, then I will be glad to explore other possibilities.

**Comment by KagakuSan** [comment]
hello @bootchk , i got same problem, but like you said that an executable file named "resynthesize" must installed in the same directory as other plugins, i have done. But i still get the same error

**Comment by SimoneStarace** [comment]
Hi @bootchk , always thanks for answering me.
Yes the file resynthesizer exits in the same folder with the other files.
![Check this out](https://i.postimg.cc/L5W3ms6W/Schermata-del-2020-03-28-12-33-28.png)
I'm the only user who is using the PC with GIMP installed that's why I removed my name on the list.
I was thinking the same about the installation. Maybe using snap isn't the best way for installing software.

**Comment by KagakuSan** [comment]
@SimoneStarace are you have passed step build and install. cause i have same problem, but i forget about build and install this intructions [Building](https://github.com/bootchk/resynthesizer/blob/master/README.md#building)

**Comment by bootchk** [comment]
Starace:  Anything I say here could be wrong.... it could be that Gimp is looking in the wrong place, and finding old Python plugins, but not the executable plugin.  You might try changing the Gimp>Preferences>Folders settings to make sure that the directory where you have installed plugins is first in the path, i.e. list of directories that Gimp searches for plugins.  I say that because I myself and others have experienced problems installing plugins into the flatpak install of Gimp.

Re snap the best choice?:  you might have more success with flatpak because Gimp org offers a flatpak build  (the Gimp website leads you to it.)  I don't think they offer a snap installation, and I don't know who produces the snap installation of Gimp.

I think both flatpak and snap use "sandboxes" and put various files like user installed plugins in places that Gimp doesn't necessarily know to search.  In other words, not in ~/.config/GIMP/... (which WAS the usual place), but in ~/snap/..../.config/GIMP/...

(Aaargh... general frustration, why there are always two, competing ways of doing the same thing: seriously: snap AND flatpak?)

I have a flatpak installation of Gimp, with resynthesizer plugin installed.  I just upgraded Gimp ( >flatpak upgrade ) to Gimp 2.10.18 (released a few weeks ago), and resynthesizer (which has not changed in a long time) still works.

**Comment by SimoneStarace** [comment]
@KagakuSan from what I have seen [here](https://templatetoaster.com/tutorials/gimp-resynthesizer-plugin/) you don't need to do those steps.
@bootchk This afternoon I have reinstalled Zorin OS because I made a mess. Anyway I have installed GIMP with flatpak (don't know why it didn't went well the installation the first time) and with flatpak the installation went better compared to snap. But still I got the same error.

I putted the plugins inside the right folder as you can see in those images:
![Image1](https://i.postimg.cc/761f1B0P/Schermata-del-2020-03-28-21-07-13.png)
![Image2](https://i.postimg.cc/8CmStxKY/Schermata-del-2020-03-28-21-09-22.png)

I really don't know why it doesn't work for me.

**Comment by ThomasRadeke** [comment]
The python files need to be marked as executable. The resynthesizer binaries and the "layer-via-copy-cut.py" files are executable, but the rest isn't.

**Comment by SimoneStarace** [comment]
@ThomasRadeke it doesn't matter because I'm running GIMP with the permission of the owner of the files. So every file has all the permission but the error is still present.

**Comment by FatBoyXPC** [comment]
I'm receiving the same error running Arch.

```
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 740, in response
    dialog.res = run_script(params)
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "/home/james/.config/GIMP/2.10/plug-ins/plugin-heal-selection.py", line 148, in heal_selection
    pdb.plug_in_resynthesizer(timg, tdrawable, 0,0, useBorder, work_drawable.ID, -1, -1, 0.0, 0.117, 16, 500)
error: procedure not found
```

```
➜  ~ uname -a 
Linux fatboyxpc 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 x86_64 GNU/Linux
➜  ~ pacman -Qi gimp
Name            : gimp
Version         : 2.10.20-1
Description     : GNU Image Manipulation Program
Architecture    : x86_64
URL             : https://www.gimp.org/
Licenses        : GPL  LGPL
Groups          : None
Provides        : None
Depends On      : babl  dbus-glib  desktop-file-utils  gegl  glib-networking  hicolor-icon-theme  openjpeg2  lcms2  libheif  libexif  libgudev  libmng  libmypaint  librsvg  libwebp  libwmf  libxmu  libxpm  mypaint-brushes1  openexr
                  poppler-data  gtk2
Optional Deps   : gutenprint: for sophisticated printing only as gimp has built-in cups print support
                  poppler-glib: for pdf support [installed]
                  alsa-lib: for MIDI event controller module [installed]
                  curl: for URI support [installed]
                  ghostscript: for postscript support [installed]
Required By     : python2-gimp
Optional For    : None
Conflicts With  : gimp-plugin-wavelet-decompose
Replaces        : gimp-plugin-wavelet-decompose
Installed Size  : 111.25 MiB
Packager        : Christian Hesse <arch@eworm.de>
Build Date      : Mon 08 Jun 2020 03:28:02 AM EDT
Install Date    : Tue 09 Jun 2020 01:40:51 PM EDT
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : Signature
```

Let me know if there's more info you need!

**Comment by SimoneStarace** [comment]
@FatBoyXPC Thanks for the reply. I don't clearly understand why the plugins don't work when I install GIMP from Flathub. Also, I did notice something really strange. I have opened the **Preference** window in GIMP and checked the Plug-ins folder like in my old [reply](https://github.com/bootchk/resynthesizer/issues/76#issuecomment-605513369) and there is something strange. The folder **/app** it exists in my file system but I can't access it. I even used the command ls -la to check on my file system but it doesn't show up. Even if I try to access it, it doesn't let me enter into the folder.
It could also be something like this kind of problem since right now I'm having another problem which is not beign able to see the layer-via-copy-cat installed.

**Comment by bootchk** [comment]
A week ago, five Gimp plugins, including resynthesizer, landed on Flathub as packaged extensions.  Enabled by changes to Gimp to define an "extension point".

But this thread seems garbled, it mentions "snap", "flatpak", and self-built installations.  If you have a specific problem, please open a new thread.

**Comment by SimoneStarace** [comment]
> A week ago, five Gimp plugins, including resynthesizer, landed on Flathub as packaged extensions. Enabled by changes to Gimp to define an "extension point".

Could you give to me the link to the plugins? I'm searching on Flathub but I can't find the them.

> But this thread seems garbled, it mentions "snap", "flatpak", and self-built installations. If you have a specific problem, please open a new thread.

You're right because everything started when I have installed GIMP through **snap**. Then I shifted to **Flatpak** and yesterday I tried to install the plugin using gimp from the **package manager** with all three cases unable to install the plugin. I made this post a little mess.

Anyway I'm currently using Flathub for install software so if the plugin works using Flathub I will personally close this thread.

**Comment by FatBoyXPC** [comment]
@bootchk I don't have an issue anymore, but I did _prior_ to building from source. Should I still open a new issue?

**Comment by SimoneStarace** [comment]
@FatBoyXPC No because I have found where are the plugins when someone installs GIMP with **flatpak**.
You just have to open your software manager and check out for GIMP (but the one as flathub as a source) and there you can simply check what extension you want to install.

I think this is the simplest solution about installing extensions.
