### ISSUE TITLE
Translation doesn't seem to be working

### ISSUE THREAD

**Issue by kwl01skz** [bootchk/resynthesizer#80]
I have found the only reynthesizer that can be recognized, it has not been translated, even though my language is Russian.

I am using ubuntu20.04 + flatpak , most plugins are not recognized correctly,
 so I can't be very sure what caused the translation to not work .

If translations are available on other people 's computers, I will try to add zh_CN translations.

**Comment by bootchk** [comment]
I do not know the complete answer, it is complicated.

Python2 is going away.  Some distributions still ship Python2 just for Gimp, and then the resynthesizer Python plugins will work. (For example, see another issue that says the Arch distribution ships a package named something like gimp-python2.)

When Gimp 3 is shipped, things will change again.  I am not sure exactly how the Python2/Python3 problem will be fixed for resynthesizer.  For example, I may need to rewrite the Python plugins.  Read some of the other issues for more information.

For now, the resynthesizer-gui plugin is the only plugin that is not Python (but C language) and that has translatable strings.  Look in the code in the /po directory for an example.  A translation file will have a line like "src/resynthesizer-gui/resynth-gui.c:156" that marks a translatable string for that plugin.

But that plugin resynth-gui uses GTK2 which is also going away (dead.)  I have already rewritten it in Python, in another branch of the repository.  I just haven't released it yet.

My advice to you: wait a little while.  Wait until Gimp3 and a new release of resynthesizer.

If you want to proceed anyway, I think it should work if you add a translation file to the /po directory, the file having just translations for the resynth-gui plugin.  If that doesn't work, I might help but would need to know specifics about what files you created.

Thanks for even considering to help with translations.

**Comment by kwl01skz** [comment]
Okay, I will look forward to it. Thank you.
By the way,  the "Sides" mean "Left and right" (like "Above and below") or "edge of the image"?

**Comment by bootchk** [comment]
Yes, "Sides" means "Left and Right."

Thanks for the suggestion, but I don't think I need to change the terminology.   I looked up the definition of "sides".  In English, the first definition is "to the left or right."  I don't mean to squelch your questions.  I am glad to consider changes in terminology, and I enjoy exploring language nuances.  Maybe the usual equivalent word in your languages has a different first meaning?

**Comment by kwl01skz** [comment]
In my understanding, it  can also include "Above and below", unless it is a very regular shape (like a cube)

**Comment by bootchk** [comment]
I am not sure I understand what our question is.  From my memory (without looking at the code, which is in the Python part), "Sides" means to crop the context to the height of the target.  In the words, the smallest horizontal band that covers the target.  When the target is not a rectangle, yes, that would include some (few in number?) pixels that are above or below some pixels of the target.

Maybe you are suggesting that the result would be better if the cropping of the context were changed, to make rectangles to the sides that are "tangent" to an irregular target but don't include any pixels that are above or below any pixels of the target.  That idea is certainly  worth considering, but in my experience, it would need experimentation, and there could be some cases where that change would produce worse results than the present algorithm.

**Comment by kwl01skz** [comment]
I just need to know that it really means "left and right", this is just a doubt in translation.
