### ISSUE TITLE
Script-Fu -> Enhance is missing

### ISSUE THREAD

**Issue by dpedrelli** [bootchk/resynthesizer#82]
I am running GIMP 2.10.20 (revision 1).  I have Python 2 32-bit & 64-bit and 3  32-bit & 64-bit.  Resynthesizer shows in the Plug-in browser.  All of the Resynthesizer filters appear under both Enhance and Map.  Script-Fu -> Enhance -> Smart remove selection is missing.  Script-Fu has entries for "Start Server," "Refresh Scripts," and "Console."

**Comment by bootchk** [comment]
"Filters>Enhance>Heal selection...." should appear.

"Enhance>Smart remove selection" is an ancient name, dating from about 2000 and the original version 0.16 of Resynthesizer.  Only very old web pages probably still refer to that ancient name.

**Comment by dpedrelli** [comment]
@bootchk That got it, thanks.  I must have been working off of older documentation.
