### ISSUE TITLE
gimp 3.0 Support

### ISSUE THREAD

**Issue by sambhavsaggi** [bootchk/resynthesizer#96]
Add support for gimp devel (2.99) packages

**Comment by bootchk** [comment]
Duplicate of #67

Please read the readme about the "deprecations" branch.  I have tested it with 2.99 but it is not for general public consumption.

**Comment by Neustradamus** [comment]
@bootchk: Thanks!

Tag:
- https://github.com/bootchk/resynthesizer/releases/tag/v3.0

Release:
- https://github.com/bootchk/resynthesizer/releases/tag/v3.0

Linked to:
- https://github.com/bootchk/resynthesizer/issues/153
- https://github.com/bootchk/resynthesizer/issues/96
- https://github.com/bootchk/resynthesizer/issues/67
